### ISSUE TITLE
Errors when loading lesson protected by Content Drip

### ISSUE THREAD

**Issue by jeherve** [woocommerce/sensei-content-drip#97] opened 2016-05-03 11:29 UTC
As a student, access a lesson that's not available to you just yet. You'll get the following errors at the top of the page:

```
Notice: Indirect modification of overloaded property WP_Query::$posts has no effect in /wp-content/plugins/sensei-content-drip/includes/class-scd-ext-lesson-frontend.php on line 94

Warning: array_shift() expects parameter 1 to be array, null given in /wp-content/plugins/sensei-content-drip/includes/class-scd-ext-lesson-frontend.php on line 94
```

**Comment by bor0** [comment] 2016-10-23 16:01
I'm not sure in what scenario this can be reproduced, as it is expected that [here](https://github.com/woocommerce/sensei-content-drip/blob/master/includes/class-scd-ext-lesson-frontend.php#L94) `$wp_query->posts` is already evaluated (even though it could be empty, it will be `array()`), because the only place that function is called is on the `the_posts` filter.

We could add a `&& !empty( $wp_query->posts )` conditional on top of [this](https://github.com/woocommerce/sensei-content-drip/blob/master/includes/class-scd-ext-lesson-frontend.php#L95) to make the code more defensive, but I'm really curious how to reproduce this first.

**Comment by pgk** [comment] 2016-11-04 10:31
@jeherve I think this should be addressed by https://github.com/woocommerce/sensei-content-drip/issues/92

**Closed by pgk** 2016-11-04 10:31 UTC
Labels: [Type] Bug

**Comment by pgk** [comment] 2016-11-04 10:36
The pr addressing this is https://github.com/woocommerce/sensei-content-drip/pull/108

**Comment by pgk** [comment] 2016-11-04 10:36
The pr addressing this is https://github.com/woocommerce/sensei-content-drip/pull/108
