### ISSUE TITLE
404 on frontend.css

### ISSUE THREAD

**Issue by lvnilesh** [woocommerce/sensei-content-drip#117] opened 2016-11-20 15:28 UTC
using master a794dc56edcec163cf49b12d71f922fac3c5f198

```
wp-content/plugins/sensei-content-drip/assets/css/frontend.css?ver=1.0.5

Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by bor0** [comment] 2016-11-22 15:54
That's weird you're seeing that error. The file is physically there if you look at https://github.com/woocommerce/sensei-content-drip/tree/a794dc56edcec163cf49b12d71f922fac3c5f198/assets/css, and also I cannot reproduce this locally, using both zip package from the release and local git build.

<img width="701" alt="screen shot 2016-11-22 at 16 51 18" src="https://cloud.githubusercontent.com/assets/1620929/20530626/4e31e00a-b0d4-11e6-8e90-9d25f9671d9b.png">

**Comment by lvnilesh** [comment] 2016-11-23 04:38
Strange that the file exists but note that it shows zero bytes. What may be causing this 404 error?

```
cd ~/wp-content/plugins/sensei-content-drip/assets/css

ls -l

total 72
-rwxr-xr-x 1 www-data www-data   618 Nov 20 15:25 admin-lesson.css
-rwxr-xr-x 1 www-data www-data   492 Nov 20 15:25 admin-lesson.min.css
-rwxr-xr-x 1 www-data www-data   473 Nov 20 15:25 admin-lesson.scss
-rwxr-xr-x 1 www-data www-data     0 Nov 20 15:25 frontend.css
-rwxr-xr-x 1 www-data www-data     0 Nov 20 15:25 frontend.less
-rwxr-xr-x 1 www-data www-data     0 Nov 20 15:25 frontend.min.css
-rwxr-xr-x 1 www-data www-data    61 Nov 20 15:25 index.php
-rwxr-xr-x 1 www-data www-data 31549 Nov 20 15:25 jquery-ui.css
-rwxr-xr-x 1 www-data www-data 24342 Nov 20 15:25 jquery-ui.min.css
```

**Comment by pgk** [comment] 2017-02-02 11:49
I can't reproduce this either, closing

**Closed by pgk** 2017-02-02 11:49 UTC
