### ISSUE TITLE
Remove lesson access

### ISSUE THREAD

**Issue by gaurav1984** [woocommerce/sensei-content-drip#222] opened 2021-04-23 14:27 UTC
The user contacted us at 3925282-zen, and they are looking to do the following

### Steps to Reproduce

- They have a course set up with lessons access given after 7 days of completing the previous lesson
- A learner completes Lesson 1 ~ 7 days pass they get access to lesson 2
- The teacher decides that the learner is not ready to have access to lesson 2 so they try to remove the access by doing the following
      1. Reset the start date for the learner ~ learner still has access to the 2nd lesson
      2. Go to Learner Management  >  _Course_  >  _lesson name_ | Bulk Learner Actions -> _Reset Progress_ the Learner still has access to the lesson

### What I Expected

- By doing either 1 or 2 actions listed above the user would lose access to the Lesson 
- **Enhancement** their Drip schedule will reset.

I checked this workflow on my test website and was able to reproduce the issue.

3925282-zd-woothemes

**Comment by gaurav1984** [comment] 2021-04-23 14:28
The user also has tried the following

- We have modified the course start dates
- We have modified the lesson start dates
- We have done "Reset Progress"
- We have done "Reset Enrollment"
- We have eliminated the student from the course and we have re-enrolled him

The result is that once you have already had access to a lesson and then we don't want you to have access to that lesson you can always access it again regardless of the Drip Schedule

**Comment by enwiss** [comment] 2021-05-24 20:01
Hi

The steps to reproduce the error are

1. We create a course with two lessons
2. Lesson two is named Drip Shedule "After two weeks"
3. The student begins the course with lesson 1/4, ends it, marks "Complete
Lesson"
4. Two weeks pass and lesson 2/4 is activated.
5. At this time we as administrators no longer believe it is appropriate
for the student to start this lesson and we want him to only have access to
lesson 1/4 and not yet be able to access lesson 2/4.
6. At this moment is where we have the problem, since, even if we do
"Delete the progress", "Reset the progress" or remove it from the course
and re-point it, if you access lesson 1/4 and do Complete Lesson You no
longer have to wait the two weeks and the class is visible, but we don't
want it to be visible to the student.


His partner reproduced the error and for that reason the incident was opened

Hi Rafael,

Thanks for getting back to us and sending the details of the workflow you
have been following to remove the learner's access to the lessons.

I was able to check and reproduce the issue on my test site. I have
submitted a report about this to our developers.

We will get back to you with their reply soon.

Best,

*Gaurav,*

Happiness Engineer: Automattic, Inc. <https://automattic.com/>

*Crowdsignal <https://crowdsignal.com/>* | *Jetpack <https://jetpack.com/>*
 | *Sensei <https://senseilms.com/>* | *WordPress.com
<https://wordpress.com/>* | *WP Job Manager <https://wpjobmanager.com/>*

We'll await for further news

Thanks and regards

**Comment by gaurav1984** [comment] 2021-05-28 10:58
Hi @renatho I followed your steps on my test site to check for the issue and in doing so landed on the correct path to resolving this issue.

Here is a Screencast of what I did https://d.pr/v/1DOBTQ

**Comment by dericleeyy** [comment] 2021-09-10 08:25
I think this might be a bug.

From our docs:

>If a learner has already been given access to a lesson, when you select that learner and that lesson, the Give Access button will change to Remove Access.

When a learner has access already, the button does not change to become Remove Access.

**Comment by renatho** [comment] 2021-09-10 23:03
> I think this might be a bug.
> 
> From our docs:
> 
> > If a learner has already been given access to a lesson, when you select that learner and that lesson, the Give Access button will change to Remove Access.
> 
> When a learner has access already, the button does not change to become Remove Access.

Thank you for reporting it @dericleeyy ! I created a PR with the fix here: https://github.com/woocommerce/sensei-content-drip/pull/227

**Comment by renatho** [comment] 2021-09-10 23:05
Closing this issue since it doesn't seem valid. See https://github.com/woocommerce/sensei-content-drip/issues/222#issuecomment-850336263 and https://github.com/woocommerce/sensei-content-drip/issues/222#issuecomment-847100753.

**Closed by renatho** 2021-09-10 23:05 UTC
Labels: [Type] Enhancement, [Pri] Normal, [Status] Queued
