### ISSUE TITLE
Time Formatting Causing Fatal Errors

### ISSUE THREAD

**Issue by annezazuu** [woocommerce/sensei-content-drip#103] opened 2016-10-21 13:16 UTC
In 482015-zd-woothemes, a user has written in documenting fatal errors on their site after changing the date format to spanish (d/m/y). 

Example of error:

`Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (23/11/2016) at position 0 (2): Unexpected character' in /var/www/nirakara/wp-content/plugins/sensei-content-drip/includes/class-scd-ext-access-control.php:223 Stack trace: #0 /var/www/nirakara/wp-content/plugins/sensei-content-drip/includes/class-scd-ext-access-control.php(223): DateTime->__construct('23/11/2016') #1 /var/www/nirakara/wp-content/plugins/sensei-content-drip/includes/class-scd-ext-access-control.php(122): Scd_Ext_Access_Control->get_lesson_drip_date(320, 17) #2 /var/www/nirakara/wp-content/plugins/sensei-content-drip/includes/class-scd-ext-access-control.php(85): Scd_Ext_Access_Control->is_absolute_drip_type_content_blocked(320) #3 /var/www/nirakara/wp-content/plugins/sensei-content-drip/includes/class-scd-ext-lesson-frontend.php(86): Scd_Ext_Access_Control->is_lesson_access_blocked(320) #4 [internal function]: Scd_Ext_Lesson_Frontend->lesson_content_drip_filter(Array) #5 /var/www/nirakara/wp-incl in /var/www/nirakara/wp-content/plugins/sensei-content-drip/includes/class-scd-ext-access-control.php on line 223`

@jeherve  suggested changing it so that we always convert `_sensei_content_drip_details_date` to a Unix timestamp before using it.

cc @pgk  to dig in and @danjjohnson

**Comment by bor0** [comment] 2016-10-23 15:13
In my case, [here](https://github.com/woocommerce/sensei-content-drip/blob/master/includes/class-scd-ext-lesson-admin.php#L304) I get `$date_string = (string [16]) 'October 29, 2016'`, which is a different format from what the comment in the code says `incoming Format:  yyyy/mm/dd`.

Additionally, if they change the format in the future again, then there is a chance inconsistencies will arise between the dates for different records in the database.

So 👍 on converting to unix timestamp before saving it, as the various possibility of date formats make it hard to match all of them properly.

**Comment by pgk** [comment] 2016-11-02 08:42
Should be addressed by 49b2e7b

**Comment by pgk** [comment] 2016-11-04 10:32
Reopening to address in a new PR

**Comment by danjjohnson** [comment] 2016-11-21 12:31
@bor0 still having trouble here, using 1.0.6-beta

Test case:
1. Go to Settings > General and set the date format to d/m/Y
2. Create/edit a lesson and set Content Drip to "on a specific date"
3. Select 30th November 2016 from the calendar

This should show as 30/11/2016, but instead it shows as 11/30/2016:
![image](https://cloud.githubusercontent.com/assets/1990037/20482745/2a6cefd2-afe6-11e6-9db3-5f9502338f50.png)

When I update the lesson, it seems to change to an almost random date - 11/06/2018
![image](https://cloud.githubusercontent.com/assets/1990037/20482780/5bd4fa38-afe6-11e6-8dc1-27d6e52ff404.png)

**Comment by danjjohnson** [comment] 2016-11-22 08:08
@bor0 ok, it works on my live test site, but not on my local test site. Could it be an issue with my local server setup?

**Comment by bor0** [comment] 2016-11-22 12:16
Hmm, what are the differences in the settings? Maybe a different tz?

**Comment by danjjohnson** [comment] 2016-11-22 14:45
@bor0 all the same settings as far as I can tell.

**Comment by bor0** [comment] 2016-11-22 15:43
That's really strange. And can you confirm that you have the fix locally in the code?

**Comment by danjjohnson** [comment] 2016-11-22 16:57
Cleared cache. The code is there. No idea why it's not working ¯\_(ツ)_/¯

**Comment by bor0** [comment] 2016-11-22 18:07
Issue was resolved after updating to latest WP core. Created related issue https://github.com/Automattic/sensei/issues/1648.

**Comment by nb** [comment] 2016-11-30 10:11
@bor0 isn’t there a way to make it work on older WordPress versions, too? I am sure there are a lot of Sensei users using WP <4.6.1. We wouldn’t want to break their installs.

**Comment by danjjohnson** [comment] 2016-12-23 15:34
Certain time formats still cause fatal errors.

Steps to reproduce:

Switch site language to Dutch
Set the date format to 'j F Y'
Create a lesson and assign it to a course.
Set the drip date to any date where the name of the month is not the same as the English name (e.g. 2 maart 2017)
When you update the lesson you get a fatal error:

Fatal error: Call to a member function getTimestamp() on a non-object in wp-content/plugins/sensei-content-drip/includes/class-scd-ext-lesson-admin.php on line 329

because DateTime::createFromFormat( 'j F Y', '2 maart 2017' ); returns false (F only works with English)

See: http://stackoverflow.com/questions/36498186/php-datetimecreatefromformat-and-multi-languages

507509-zd-woothemes

**Comment by aheckler** [comment] 2017-01-11 16:07
518091-zd-woothemes

**Comment by pgk** [comment] 2017-02-01 11:36
Closing this, conversation continues in #120

**Closed by pgk** 2017-02-01 11:36 UTC
Labels: [Type] Bug

**Comment by aheckler** [comment] 2017-02-06 19:15
528235-zd-woothemes
