### ISSUE TITLE
Lessons dripped by date are showing the content if accessed

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/sensei-content-drip#79] opened 2015-10-27 22:06 UTC
If you set a lesson to drip at a date in the future like 20/12/2015 for example with the parameter **On a specific date** after the learners starts taking the course if free or purchases a paid course they can see the content of the lesson.

Screenshot of drip settings on a new course and lesson.

Screenshot: http://cld.wthms.co/1fHUP/3hyoLh0k

Below is a screenshot as a normal customer who purchased the course viewing the lesson with the future drip parameters set.

Screenshot: http://cld.wthms.co/17qGr/2pDNnJ7s

it also does not display the excerpt when set that would usually replace the main content.

**Comment by aheckler** [comment] 2017-02-03 14:41
Closing this because I can't reproduce it. @stuartduff feel free to re-open if you still can.

**Closed by aheckler** 2017-02-03 14:41 UTC
Labels: [Type] Bug
