### ISSUE TITLE
Restrict access to quizes and media attachments

### ISSUE THREAD

**Issue by jeherve** [woocommerce/sensei-content-drip#99] opened 2016-05-27 14:56 UTC
When restricting content to a specific lesson, learners can still access both the quizes for that lesson, as well as the media attached to the lesson. They should only become available once the lesson becomes available.

Reported in 424659-zd-woothemes

**Comment by pgk** [comment] 2016-11-07 10:04
Can Reproduce for Quizzes

**Comment by pgk** [comment] 2016-11-07 12:10
@danjjohnson 3d26b0d addresses quiz content and status message. Should we also be changing the quiz title when it's parent lesson hasn't dripped yet?

**Comment by danjjohnson** [comment] 2016-11-08 13:28
Works for me (the quiz content and controls are hidden when viewing the quiz directly) but media (from Sensei Media Attachments) is still shown in the lesson page.

**Comment by pgk** [comment] 2016-11-08 13:43
@danjjohnson should be addressed in commit 	0663764

**Comment by danjjohnson** [comment] 2016-11-08 13:45
Fixed :)

**Closed** 2016-11-11 14:46 UTC
Labels: [Priority] High, [Type] Bug
