### ISSUE TITLE
Drip Schedules does not get saved with Yoast installed

### ISSUE THREAD

**Issue by dericleeyy** [woocommerce/sensei-content-drip#221] opened 2021-02-23 04:46 UTC
### Steps to Reproduce
1. Enable Yoast plugin
2. Edit and save the drip schedule of a lesson
3. Refresh the page to view the changes

### What I Expected
Changes are saved

### What Happened Instead
The drip schedule is not saved

The issue seems related to the other issue fixed by https://github.com/Automattic/sensei/pull/3982

### PHP / WordPress / Sensei Content Drip / Sensei LMS version
Content Drip 2.1.0
SWPC 3.8.1.2.3.2
Yoast 15.8
WP 5.6.2

### Context / Source
3745591-zen

**Comment by dericleeyy** [comment] 2021-02-23 08:06
3763307-zen

**Comment by bindlegirl** [comment] 2021-03-04 12:53
Possibly related issues reported in 3784057-zen and 3735183-zen
The problem in those tickets is that the emails are not being sent until Yoast is disabled.

**Comment by renatho** [comment] 2021-03-05 15:20
I could reproduce the issue with Yoast 15.8. But it seems to be working with 15.9.1 (released yesterday).
In this case, I'm closing this issue.

**Closed by renatho** 2021-03-05 15:20 UTC
Labels: [Pri] High, [Status] Queued, [Type] Bug
