### ISSUE TITLE
When using SiteOrigin Page Builder, lesson content is available before it is dripped

### ISSUE THREAD

**Issue by alexsanford** [woocommerce/sensei-content-drip#166] opened 2019-05-09 20:45 UTC
To reproduce:

- Install SiteOrigin Page Builder - https://siteorigin.com/page-builder/
- Go to Settings > Page Builder.
- Check "Lessons" under "Post Types" and save settings.
- Create a lesson using the page builder, and add it to a course.
- Set the drip date for the lesson to a date in the future.
- Log in as a non-admin user and start taking the course.
- Attempt to view the lesson. You will see the content, even though it hasn't dripped yet.

Reported in 2012719-zen

**Comment by donnapep** [comment] 2019-10-03 17:19
Closing as I'm not able to reproduce this. I get the "This lesson will become available on..." notice.

**Closed by donnapep** 2019-10-03 17:19 UTC
